[tool.poetry]
name = "pyupdater"
version = "4.1.0"
description = "Fork of PyUpdater"
authors = ["Jayme Gordon <jaymegordo@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
appdirs = "^1.4.4"
bsdiff4 = "^1.2.1"
certifi = "^2021.5.30"
dsdev-utils = "1.0.5"
pyinstaller = "^5.3"
PyNaCl = "^1.4.0"
stevedore = "<4.0"
urllib3 = "<2.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
autopep8 = "^1.5.7"
pre-commit = "^2.15.0"

[tool.poetry.scripts]
pyupdater = "pyupdater.cli:main"


[tool.pyright]
ignore = ["pyupdater", "tests", "dev"]
reportWildcardImportFromLibrary = "none"
reportUnboundVariable = "information"
reportMissingImports = "information"
reportGeneralTypeIssues = "information"
reportOptionalIterable = "none"
reportOptionalMemberAccess = "information"
reportOptionalSubscript = "information"
reportInvalidStringEscapeSequence = "information"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
